/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.6.0
 *
 * Project: 'IOTKit_CM33_ns+V2MMPS2' 
 * Target:  'V2MMPS2' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "IOTKit_CM33_FP.h"



#endif /* RTE_COMPONENTS_H */
